### ISSUE TITLE
GDG Almería vuelve a estar activo

### ISSUE THREAD

**Issue by Indavelopers** [GDGSpain/gdg.es#64]
Info:
Web: https://www.meetup.com/es-ES/GDGAlmeria/
Facebook: https://www.facebook.com/GDGAlmeria/
Twitter: https://twitter.com/gdgalmeria
G+: https://plus.google.com/+GDGAlmer%C3%ADa

Gracias!

**Comment by Borjagodoy** [comment]
Necesitamos también una imagen bonita de almería :)

**Comment by Indavelopers** [comment]
Ésta nos vale!
https://github.com/GDGSpain/gdg.es/blob/develop/data/images/cities/almeria.jpg

**Comment by abdonrd** [comment]
Added! 😁
